fix downstream link errors
* openssl crypt library depends on pthread

/home/smanders/src/externpro/_bldx/externpro_19.06.1-30-ga3a9660-p-gcc740-64/lib/libcrypto_1.1.1c.a(threads_pthread.c.o): In function `CRYPTO_THREAD_lock_new':
threads_pthread.c:(.text+0x45): undefined reference to `pthread_rwlock_init'

and other undefined references to
* pthread_rwlock_rdlock
* pthread_rwlock_wrlock
* pthread_rwlock_unlock
* pthread_rwlock_destroy
* pthread_once
* pthread_key_create
* pthread_setspecific
* pthread_key_delete
* pthread_atfork
* pthread_getspecific

* define OPENSSL_NO_STATIC_ENGINE to fix undefined references to engine_load_[afalg|padlock]_int

/home/smanders/src/externpro/_bldx/externpro_19.06.1-30-ga3a9660-p-gcc740-64/lib/libcrypto_1.1.1c.a(init.c.o): In function `ossl_init_engine_afalg_ossl_':
init.c:(.text+0x65): undefined reference to `engine_load_afalg_int'

/home/smanders/src/externpro/_bldx/externpro_19.06.1-30-ga3a9660-p-gcc740-64/lib/libcrypto_1.1.1c.a(init.c.o): In function `ossl_init_engine_padlock_ossl_':
init.c:(.text+0x85): undefined reference to `engine_load_padlock_int'

* openssl crypt library depends on dl

/home/smanders/src/externpro/_bldx/externpro_19.06.1-30-ga3a9660-p-gcc740-64/lib/libcrypto_1.1.1c.a(dso_dlfcn.c.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'

another other undefined references to
* dlerror
* dladdr